input_format: profdata
coverage_service: cobertura_xml
output_directory: slather-report
scheme: TestUnitTestAppTests
workspace: TestUnitTestApp.xcworkspace
xcodeproj: TestUnitTestApp.xcodeproj
source_directory: ../TestUnitTestApp
ignore:
    - ../**/*/Xcode*
    - ../core/*
